<?php
include '../templates/header.php';
?>
    <section id="renewable-energy">
        <h2>Renewable Energy</h2>
        
        <article class="renewable-energy">
            <h3>Solar Energy</h3>
            <img src="../images/solar-energy.jpg" alt="Solar panels" class="article-image">
            <p>Solar energy harnesses the power of the sun through photovoltaic cells or solar thermal systems. It is one of the most widely used renewable energy sources due to its abundance and decreasing costs.</p>
            <h4>Advantages of Solar Energy</h4>
            <ul>
                <li>Reduces electricity bills</li>
                <li>Decreases carbon footprint</li>
                <li>Low maintenance costs</li>
            </ul>
            <h4>Challenges</h4>
            <ul>
                <li>Intermittent energy supply due to weather conditions</li>
                <li>High initial setup costs</li>
            </ul>
        </article>

        <article class="renewable-energy">
            <h3>Wind Energy</h3>
            <img src="../images/wind-energy.jpg" alt="Wind turbines" class="article-image">
            <p>Wind energy is generated by converting the kinetic energy from wind into electricity using wind turbines. It is a clean and efficient method of producing power, particularly in windy areas.</p>
            <h4>Advantages of Wind Energy</h4>
            <ul>
                <li>Low operational costs</li>
                <li>Reduces greenhouse gas emissions</li>
                <li>Can be deployed in various scales</li>
            </ul>
            <h4>Challenges</h4>
            <ul>
                <li>Noise and visual impact</li>
                <li>Requires suitable wind conditions</li>
            </ul>
        </article>

        <article class="renewable-energy">
            <h3>Hydropower</h3>
            <img src="../images/hydropower.jpg" alt="Hydropower dam" class="article-image">
            <p>Hydropower generates electricity by harnessing the energy of flowing water. It is one of the oldest and most established forms of renewable energy, with large-scale dams and small-scale hydro systems available.</p>
            <h4>Advantages of Hydropower</h4>
            <ul>
                <li>Reliable and consistent energy source</li>
                <li>Provides flood control and water supply</li>
                <li>Can support local ecosystems</li>
            </ul>
            <h4>Challenges</h4>
            <ul>
                <li>Environmental impact on aquatic ecosystems</li>
                <li>High initial construction costs</li>
            </ul>
        </article>
    </section>

<!-- Go to Top Button -->
<a href="#" class="go-to-top" id="go-to-top">
    <i class="fas fa-arrow-up"></i>
</a>


<?php
include '../templates/footer.php';
?>
